### ISSUE TITLE
Cannot unzip the zip created by this addon

### ISSUE THREAD

**Issue by ianpetzer** [ember-cli-deploy/ember-cli-deploy-fastboot-app-server#3]
Hi there,

Thanks so much for this awesome addon. 

I'm having a problem with `fastboot-s3-downloader running into errors when it tries to unzip the zip created by `ember-cli-deploy-fastboot-app-server`. The specific is  `error:  invalid compressed data to inflate`

I also run into this issue if I try to unzip from the command line.

I’ve traced this to an issue in adm-zip, https://github.com/cthackers/adm-zip/issues/102  …. The TLDR is that problem seems to occur when adm-zip tries to zip files that use compression. In my case jpg files

**Comment by LevelbossMike** [comment]
Hi @ianpetzer,

mmh I have not run into this in my test project. If this is a problem with adm-zip the easiest way most likely is to move to a different zip library. We aren't doing too much with adm-zip only zipping the dist-folder.

Can you confirm that this indeed is fixed by using a different zip-library?

**Comment by ianpetzer** [comment]
Hi there,

Does the zip need to be done sync? Or can it be done async?

**Comment by LevelbossMike** [comment]
promises work you just need to return the promise from a deploy-hook

**Comment by ianpetzer** [comment]
ok, I will have a look

**Comment by daniel-de-wit** [comment]
@ianpetzer Would you be willing to check if #4 fixes your problems as it did for me?

`"ember-cli-deploy-fastboot-app-server": "https://github.com/daniel-de-wit/ember-cli-deploy-fastboot-app-server/tarball/17e3ae3581ea257af305f7d7e7e6b168dc22e8cd"`

**Comment by ianpetzer** [comment]
Hi Daniel,

It does work, but I think that your PR is telling adm-zip not to compress
any files at all, as my zip has gone from 8mb to 26mb using this PR.

I was trying to fix this using an alternate zipping library and you can see
my current efforts here:
https://github.com/TimbuktuTravel/ember-cli-deploy-fastboot-app-server/tree/manual-promise

That branch works successfully for creating the zip, but the one test is
failing because I'm struggling to unzip the created zip in the test.

I think this branch looks promising if we could specify which file types to
exclude from the zip process?
